# Generated by Django 5.2.7 on 2025-10-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
