# Generated by Django 5.2.7 on 2025-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_fec_ing_producto_piezas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='piezas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
