# Generated by Django 5.2.7 on 2025-10-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_activo_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='costo',
        ),
    ]
